source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SimpleDemo', :exclusive => true do
  pod "SwiftLayout", :path => "../../"
end

target 'SimpleDemoTests', :exclusive => true do
  pod "SwiftLayout", :path => "../../"


end
